monzo/typhon

- test/stub_server.go
> Stub server: Add comments and update to match conventions

- server/endpoint.go
Handle unmarshaling nil requests, by just using a blank request. This means if you pass a blank string `""` rather than `"{}"` with a json content type the behaviour will now be the same.
> Handle unmarshaling nil requests

- server/rabbitmq.go
Fix a race condition where observers were notified of the server connecting before the server started consuming messages (and both declared and bound to the exchange) thereby dropping messages sent immediately after. Also made this non blocking to prevent deadlocks if the observer had timed out or stopped listening.
> Fix race condition notifying observers before consuming

- client/rabbitmq.go
- client/request.go
- errors/errors.go
- errors/marshaling.go
- errors/marshaling_test.go
- errors/stack/stack_test.go
- example/handler/callhello.go
- example/handler/hello.go
- example/main.go
- server/amqp_request.go
- server/endpoint.go
- server/endpoint_registry.go
- server/rabbitmq.go
- server/request.go
- server/server.go
- test/error_passing_test.go
- test/helpers.go
- test/server.go
- test/stub_server.go
- typhon_test.go
> Update org name and imports

- message/interface.go
- message/proto.go
These can use the "real" JSON marshaler.
Don't merge this until mondough/wearedev#254 is merged, pls.
> Remove proto JSON special case

- message/json.go
- message/json_test.go
> Allow JSON unmarshmaling to native types

- message/json.go
- message/json_test.go
> More fixes for unmarshaling native types as JSON

- rabbit/rabbit.go
- rabbit/rabbittransport.go
This replaces the dedicated long lived reply queue with direct reply-to as described here: https://www.rabbitmq.com/direct-reply-to.html
> Use direct reply-to instead of long-lived dedicated queue

- .travis.yml
- message/json.go
- message/json_test.go
> Allow unmarshmaling JSON values into interface{}(nil)

- message/req.go
- message/rsp.go
> Fix (erroneous) go vet error in Go 1.7

- client.go
Access to the response is guarded by the `done` channel so it is redundant
> Remove unnecessary mutex in ResponseFuture

- terrors.go
Can be merged once the [terrors PR](https://github.com/monzo/terrors/pull/2) is in.
> Support status PreconditionFailed

- .travis.yml
- client.go
- e2e_test.go
- listener.go
- mock/mocktransport.go
- request.go
- response.go
- timeout.go
This allows, for example, requests over Unix domain sockets (and this is what is tested). Also fixes a potential Goroutine leak 🐛 , and refactors for Go 1.7+ 🤖
> Allow non-TCP communication 🔌

- client.go
- e2e_test.go
In most uses, cookie jar and redirect following functionality is undesirable in Typhon applications, and if it is needed should be provided explicitly via filters. This switches the underlying client code to use `net/http` `RoundTripper`'s rather than `Client`;s, which do not have this magic built-in. 🍪 ✨
> Use RoundTripper for client requests

- router.go
- router_test.go
This is useful for recording the path in metrics where we want to see statistics aggregated by "endpoint."
> Allow retrieving the matched pattern from a Router

- response.go
> Fix comment

- http.go
Since `net/http` started managing contexts (in Go 1.7), it already provides the context cancellation behaviour we want in servers. As we no longer support Go ≤1.6, there is no need for the explicit context management code that exists in `HttpHandler`. Our E2E tests verify that this remains the case.
Benchmarks show that this saves a Goroutine and 5 memory allocations per request. 🏎
> Remove context cancellation management code from HttpHandler

- router.go
- router_test.go
We have a filter in our private code that does something similar to this, but it requires every service to set it up it explicitly in its `main.go`, which is cumbersome and often gets forgotten about.
This PR introduces `RouterForRequest`, which can be called on a `Request` to get the `Router` that dispatched it.
> Provide a hook to get the Router used to dispatch a request 🎣

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/labstack/echo/Gopkg.lock
- vendor/github.com/labstack/echo/Gopkg.toml
- vendor/github.com/labstack/echo/Makefile
- vendor/github.com/labstack/echo/bind.go
- vendor/github.com/labstack/echo/context.go
- vendor/github.com/labstack/echo/echo.go
- vendor/github.com/labstack/echo/go.mod
- vendor/github.com/labstack/echo/go.sum
- vendor/github.com/labstack/echo/group.go
- vendor/github.com/labstack/echo/log.go
- vendor/github.com/labstack/echo/router.go
Updated `labstack/echo` to fix a routing bug: https://github.com/labstack/echo/issues/1052
v3.3.7 release notes: https://github.com/labstack/echo/releases/tag/v3.3.7
- Update dependencies (#1194)
- Simplify REALIP method (#1193)
- Expose stdLogger (#1196)
- Add error variable for too many request (#1181)
- Support internal error when Bind() data #888 (#1164)
- The logging interface add SetHeader method (#1092)
- Add common error variable (#1200)
- Fix node's parameter names assignment problem. (#1201) **<- relevant fix**
- Extend proxy middleware. (#1203)
- Proxy: Better errors + remote custom TLS (#1197)
- Replace http constants with stdlib ones
- Delete useless goto statements (#1208)
- Add back exported HTTP method constants (#1209)
> ⬆️ Update labstack/echo to v3.3.7

- router.go
This was an artefact from the development of #109.
> Remove unused Router.re field ✨

- http.go
Switches return type to a pointer.
> Fix to avoid allocation on httpChunkBufPool.Get

- response.go
In order to debug some recent [failures](https://sentry.io/organizations/monzo/issues/3225758327/events/e1b404a207bb4507beed64e119c8d150/?project=6290212), it seems like it'd be useful to include the content-type and what we tried to decode it as.
> Include more information in errors about what we failed to decode.

- http.go
[Certain HTTP status codes don't allow writing a body](https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/net/http/transfer.go;l=456-466;drc=d8762b2f4532cc2e5ec539670b88bbc469a13938), so we should check for these same set of
status codes before attempting to write the body (in [`copyChunked`](https://github.com/monzo/typhon/blob/master/http.go#L122) and [`io.CopyBuffer`](https://github.com/monzo/typhon/blob/master/http.go#L131)) to prevent
unnecessarily logging an error when the call to `Write` returns `http.ErrBodyNotAllowed`.
> Don't write body for certain status codes
