client/client.go, example/handler/hello.go, example/main.go, server/endpoint.go, server/rabbitmq.go, server/response.go, server/server.go, test/mock.go, test/test.go
=> More server tweaks

rabbit/rabbit.go, server/rabbitmq.go, server/server.go, test/server.go, typhon_test.go
Allow `Close()` to be called on the server, terminating the AMQP connection, and shutting down the server listening loop.
Also move the test server to the test package, so we can reuse it from other packages
=> Separate test server, allow remote Close()

client/rabbitmq.go
Writing to a closed channel results in a panic. This means if a client times out, and closes its reply channel, but a reply _was_ sent, receiving this causes a runtime panic.
By not closing the channel we allow a response to come back, and be written into the channel, at which point it will fall out of scope at both ends and the garbage collector will pick it up at some point.
Separately we should be manually collecting timed out responses from the inflight registry after a period of time - otherwise in the case we never receive a response the channel will never be garbage collected.
=> Fix typo and potential panics

client/rabbitmq.go, rabbit/channel.go, rabbit/rabbit.go, server/amqp_request.go, server/rabbitmq.go, test/helpers.go
=> Fix various bugs including 100% cpu usage on connection close

client/client.go, client/rabbitmq.go, client/request.go, client/response.go, server/amqp_request.go, server/endpoint.go, server/rabbitmq.go, server/request.go, test/error_passing_test.go, test/helpers.go, typhon_test.go
Refactoring to make the interfaces a little more generic, and support raw requests in multiple encodings - allowing us to support JSON on the wire between services, and therefore push raw JSON requests in from an API.
=> Refactoring to support RPC

test/helpers.go, test/stub_server.go
Currently the stub server binds on a wildcard routing key, which means this can conflict with other 'real' services bound on the same exchange (useful in more complex tests). This changes the stub server to only support a single service per instance, though multiple instances can be created, with the service name provided on creation. Multiple endpoints for that service can then be registered & stubbed.
=> Move service name to the stub server, rather than endpoints

client/rabbitmq.go, rabbit/channel.go
Change routing & binding on rabbitmq to send message just to the service's name, and bind with just the service name, rather than also specifying the endpoint in the routing key and binding on a wildcard. 
Bind on `service.thing` rather than `service.thing.#`
Send to `service.thing` rather than `service.thing.someendpoint`
This makes routing easier to reason about, and simpler, as we don't bind per endpoint anyway; and the `server` package deals with invalid endpoints anway.
=> Update inter-service routing

rabbit/rabbit.go
Rather than in `init` so that we only do this when creating a connection, keeping log output until we try to connect.
=> initialise env vars inside new connection

client/rabbitmq.go, server/rabbitmq.go
Otherwise we connect immediately as the default client and server are package level variables, and spew a ton of log output.
=> Correctly lazily initialise rabbitmq connections

mock/mocktransport.go
The caller can then retrieve the automatically-set request ID. This mirrors the behaviour of the Rabbit transport more closely.
=> Copy the request in a mock transport *after* its ID has been set

message/interface.go, message/rsp_test.go, rabbit/rabbittransport.go, run_tests.sh, transport/test.go, typhon.go
Decided that they don't make any sense on a `Response`… they were ambiguous at best. :bomb:
=> Make Service and Endpoint request-only fields

.travis.yml, rabbit/rabbittransport.go
Catch two places where an interface conversion wasn't checked for success, which triggers an unrecovered panic (and therefore service exit). :boom: 
Reproducible by sending a request with a non-string `"Content-Encoding"` header to the channel the transport listens on, which triggers the panic. :fire:
=> Catch two unchecked interface conversions

client.go, listener.go, response.go
This looks to be the source of a goroutine bug. Where control escapes the containing functions here, there's a good chance cancel() may have already been called – if so, this is a no-op.
=> Ensure to cancel contexts

client.go, e2e_test.go, http.go, router_test.go, server.go, timeout.go, timeout_test.go
* `ExpirationFilter`: An admission control filter which rejects requests if they are already cancelled
* Removed the timeout override functionality from `TimeoutFilter`; I suspect it is causing some issues, and in general shouldn't be used.
=> ExpirationFilter

router.go, router_test.go
This resolves a common frustration where two "conflicting" paths like `{/, /:foo}` cannot be registered.
=> Switch out router internals

request.go, response.go
These errors are returned to the caller (either directly or as a field on the response). The caller should be able to decide whether they warrant a log line or not.
=> Remove log lines

.travis.yml, buffer.go, e2e_test.go, request.go, response.go
For small requests it is not desirable to chunk the body as it means intermediary proxies (like linkerd) cannot retry the request transparently.
Go's logic for deciding when to chunk a request is subtle and a bit [magic](https://github.com/golang/go/blob/26708439ecb4dc923149b17eb522df46dcc2fb23/src/net/http/transfer.go#L150-L186), but this prevents chunking behaviour when `Encode()` is called before sending the response off.
=> Don't chunk non-streaming request bodies 🎁

README.md, client.go, e2e_test.go
An `http.RoundTripper` was used in the default Typhon clients, but was not exposed. This allows callers to modify it.
=> Expose RoundTripper so it can be customised by callers

.editorconfig, README.md
…and add an `.editorconfig` to prevent things like trailing spaces being stripped in Markdown files.
=> Fix up README file

buffer.go, client.go, e2e_test.go
Previously when a caller used an infinite context (eg. `context.Background()`) to make a request, this would cause a resource leak as Typhon was waiting for the context to be cancelled to `Close()` the body.
This change ensures request bodies are additionally closed when they are fully read, and adds tests to ensure no goroutines are leaked.
=> Fix leak when infinite contexts are used to make requests 🚰

buffer.go, client.go, e2e_test.go, filter.go, http.go, request.go, service.go
This contains various improvements to context handling, with the goal of eliminating context goroutine leaks. Specifically:
* Request cancellation behaviour can be controlled by using only context cancellation. To eliminate some complexity, remove the cancellation hooks from `ResponseFuture` (which are not used in Monzo's code anyway)
* The context library contains some performance optimisations when dealing with its own context types. For users of Typhon, it is common to use a Request as a context, preventing these performance optimisations from working properly. Internally, Typhon will now unwrap these contexts.
* If a context can never be cancelled, it returns a `nil` channel on `.Done()`. In this case, don't kick off a background goroutine that responds to cancellation in the client.
=> Context handling

request.go, response.go, terrors.go
We think that these convenience copies _may_ be the source of some memory leaks. 🚰
=> When copying bodies into a bufCloser, close the source Reader 🚪

buffer.go, client.go
After getting read error on a response body, it's very unlikely (perhaps impossible) that subsequent reads would be useful, and it's better to release its resources than perhaps hold onto them forever.
Also, this PR makes Typhon tolerant of reads of response bodies that are exactly their `ContentLength`.
=> Close a response body on any read error, or when exhausted 🌪

buffer.go, e2e_test.go, request.go, request_test.go, response.go, response_test.go
`Request.Decode()` and `Response.Decode()` are convenience methods that we use extensively for unmarshalling HTTP bodies. These are not suitable as methods that can be called repeatedly to yield multiple values in a streaming fashion. These methods' implementations however, used `json.Decoder` internally, which _is_ meant for streaming use.
The problem with this is that `json.Decoder` may not read the entire stream: quite reasonably it reads only as much as it needs in order to yield a value, and presumes the stream is infinite. The way this was used inside `.Decode()` meant that a response body may never get closed. That's because it's common for a response body to be terminated with new line (`\n`) character, which the `Decoder` may leave unread. This would mean that the `doneReader` …
=> Automatically close request/response bodies when they are decoded

e2e_test.go, http.go, request.go, response.go
In #79 I explicitly disabled body chunking for all response bodies which are buffered before being sent. This improved performance and ensured intermediary proxies can retry small bodies, but it is not desirable when the body is actually quite large. In Monzo's case, if the body size exceeded the maximum we've configured in linkerd, it would fail outright.
This puts a 5MB cap in place, above which any buffered body will be chunked when it's sent.
Fixes PLAT-1321.
=> Automatically buffered chunk response bodies which exceed 5MB

e2e_test.go, router.go, router_test.go
`Router` is a fairly crucial piece of functionality in Typhon, used internally at Monzo in basically every backend service – often multiple times. However it's also poorly tested and has subtle behaviour that can be hard to understand.
This change simplifies `Router` somewhat so it's no longer an interface. The rest of Typhon doesn't really care about `Router`s – it only sees the `Service`s that are materialised from them – so it didn't make sense to have an interface adding a layer of indirection. Calling code should not need to be modified so this is not a breaking change.
`"*"` can now be passed as a method name to `Register` if a caller wants all methods for a given path to be routed to a single service. Under the hood, `*` is expanded to a set of {`OPTIONS`, `GET`, `HEAD`, `POST`, …
=> Improvements to Router 🔀

router.go
Some code exists that reads in a way we'd quite like to preserve. `NewRouter().Serve()`, for instance.
=> Use value receivers for some methods of Router

e2e_test.go, response.go, terrors.go
`Response` already inherited a `Request` field from `http.Response`, but it wasn't used and had the wrong (non-Typhon) type. The `Response` type also already contained a `ctx` field with the request's context.
There's now a `Request` field containing the Typhon Request `that` is being responded to, which is more useful.
=> Make it possible to get the Request for a Response 👯‍♀️

.travis.yml
Travis build was failing because golint's canonical import path has been moved.
=> Fix golint path for Travis

terrors.go
This should make it a little clearer the mapping between Terror type and HTTP code
=> Add HTTP status codes in comments to make referencing easier

e2e_test.go, http.go, http_darwin.go, http_linux.go, http_other.go, util_test.go
When a client disconnects, Typhon currently slogs an error like this:
```
1537553768766857000 [Error] Error copying response body: write tcp 127.0.0.1:54775->127.0.0.1:54778: write: broken pipe
```
This isn't fantastically helpful and unless you're familiar with the guts of Linux, you would be forgiven for not grokking that "broken pipe" in this circumstance is a perfectly normal thing to happen, and isn't indicative of a server malfunction.
Typhon now downgrades this type of "error" to a debug event, which is really all this situation should be to an operator.
Other changes include a new test to make sure that `Streamer.Write` doesn't block forever when a client disconnects, and a refactor of the e2e tests to move them to a "vanilla" test style instead of using a cumbersome test suite.
=> Improved error handling for client disconnections ☎️

buffer.go, client.go, doc.go, e2e_test.go, errors.go, filter.go, http.go, request.go, request_test.go, response.go, response_test.go, router.go, server.go
This change:
* improves Typhon's `godoc` documentation, providing examples where they might be helpful and improving the quality of the writing ✍️
* removes the unnecessary `HttpServer` method; callers are better off constructing their own `http.Server` directly 🗑
* allows an `io.Reader` to be passed to `request.Encode()` and `response.Encode(), which makes working with `Streamer` in particular more pleasant 🏞
* adds a test for HTTP/2.0 full-duplex communication 🔀
=> Christmas sparkle 🎄✨

router.go, router_test.go
Common pattern of returning `typhon.Response{Error: ...}` on error means
that error responses can not be correlated back to the requests.
When routing requests to a Service, set the Request on the response if
is hasn't already been set.
=> Typhon: Set response Request when routing

buffer.go, e2e_test.go, request.go, response.go, response_test.go
Try to set content length correctly when using `Write()` and `Writer()` methods; only use chunked encoding with content length of -1 when the length is large, or when the handler specifically sets the body to a streamer or another io.Reader. Since the HTTP2 changes were merged, `rsp.Write([]byte("hello"))` would have content length set at -1, and chunked encoding would be used. This led to regressions where callers weren't happy with chunked encoding.
=> Set content length in the request/response Write method

router.go
When a typhon router handles a request it adds a reference to itself (the router) into the context within the request. This is useful in a variety of contexts, for example we want to tag metrics with the router pattern that the request was matched against (using the path directly can result in a cardinality explosion if the path is dynamic).
Prior to this pull request we used a context key that was an anonymous empty struct however we observed panics after a filter was introduced within our code base that uses the same key. By using a type definition that is itself an empty struct we avoid this collision.
=> Use custom type for router context key

response.go
It is a bad practice to set variables that will not be used later. Especially in a encoder/decoder that is possibly used frequently.
The variable `err := error(nil)` should be set after the possible return of `r.Error` otherwise it might end up not being used at all.
=> ineffectual assignment to err

.travis.yml
Add Go 1.12 + 1.13 to the versions that are tested by Travis.
=> Update tested Go versions

h2c.go
We're matching envoy and grpc by making this unlimited. There's no
particular reason to do otherwise, and servers that need to do so can
set up their own http2 server.
=> Set MaxConcurrentStreams to uint32_max

Gopkg.lock, response.go, response_test.go, vendor/github.com/monzo/terrors/.travis.yml, vendor/github.com/monzo/terrors/errors.go, vendor/github.com/monzo/terrors/factory.go, vendor/github.com/monzo/terrors/stack/stack.go
This PR adds support for wrapping downstream errors in the `Response` `.Decode` method.
Our goal here is to prevent downstream errors from propagating across service boundaries by default. This would mean that downstream `not_found` errors are converted into `internal_service` errors by default (with the underlying `not_found` error preserved as a _cause_ on the newly created error).
The implementation uses a context value to introduce this behaviour in a way that makes it configurable for callers. We'd like to experiment with this behaviour in our own services before recommending it and so we need to be able to enable it on a per-service basis.
We tried first to implement this as a filter, however, when creating a new error within a filter the stack trace doesn't include the entire call …
=> [BP-513] Add support for wrapping downstream request errors

Gopkg.lock, errors.go, vendor/github.com/monzo/terrors/errors.go, vendor/github.com/monzo/terrors/factory.go
This updates `typhon` to understand the the `RateLimited` error from terrors, and maps it to an HTTP 429.
=> Update terrors, add RateLimited mapping

metadata.go, metadata_test.go, request.go, request_test.go
This allows us to attach and to retrieve metadata on a Typhon request by use of the context. This is useful for scenarios when the caller doesn't have direct access to the underlying HTTP request.
=> Add support for setting metadata through context

errors.go, request.go, response.go, response_test.go
While reading [the proposal for API standards at Monzo](https://www.notion.so/monzo/API-Standards-4f1268b9bb3741749939ea7f16466fd5), I noticed we don't have a method to construct a Typhon response to a request _and_ set its HTTP status code at the same time.
This means that to return specific HTTP status codes from our APIs, the application code needs to set the status code on the response returned by the `Response` method.
For example, the new API standards suggest returning `201 Created` in response to a `PUT` request that creates a new entity. To do this with Typhon, we would write something along these lines:
```
rsp := req.Response(&MyResponseType{})
rsp.StatusCode = http.StatusCreated
return rsp
```
This PR adds a method `ResponseWithCode` to `Request`, so that we could do this …
=> Add ResponseWithCode method to Typhon request

buffer.go, e2e_test.go, http.go
If a server is using `typhon.Streamer()` and encounters an error that prevents it from writing the next chunk of data to the response (e.g. failed to read the next record from the database), there is currently no way for the server to signal to the client that streaming terminated unsuccessfully. (Besides simply stopping writing and not calling `streamer.Close()` so the client times out (and leaking a goroutine on the server), or encoding some sort of application-level error into the response body). 
For example:
```go
func streamingService(req typhon.Request) typhon.Response {
body := typhon.Streamer()
go func() {
for {
data, err := readNextData(...)
if err != nil {
// what should I do here?
}
}
body.Close()
}()
return req.Response(body)
}
```
Not having an obvious blessed path for …
=> Enable aborting streamer with error

errors.go
There is some non-obvious behavior inside `ErrorFilter` that we had to figure out whilst debugging an issue recently. We tried to document that.
=> Document the behavior inside ErrorFilter

request.go, request_test.go, response_test.go
This PR does a few things:
1. In response to Daniel's comment on the protobuf PR [here](https://github.com/monzo/typhon/pull/127#discussion_r750562509), this makes Typhon use only regular JSON or protobufs
2. ~~Adds new EncodeAsProtoJSON to encode a message as protojson~~
3. Maps Encode to point at EncodeAsProtobuf
4. ~~Blocks requests with a non-standard content-type from Typhon~~
=> Encoding / Decoding changes in protobuf branch

request_test.go, response.go, response_test.go
Some code internally expects these to always be terrors. Since that was the behaviour in the past for all errors, this PR replicates the same logic for consistency
Also includes tests to make sure we don't break this invariant
=> Make sure Encode and Decode functions return terrors errors

client.go, e2e_http1_test.go, e2e_http2_test.go, e2e_test.go
This PR rebases and builds on https://github.com/monzo/typhon/pull/121 to support HTTP2 Prior Knowledge using a context flag
Prior Knowledge connections are discussed in [section 3.4 of the HTTP/2 RFC](https://tools.ietf.org/html/rfc7540#section-3.4):
```
A client can learn that a particular server supports HTTP/2 by other
means.  For example, [ALT-SVC] describes a mechanism for advertising
this capability.
A client MUST send the connection preface (Section 3.5) and then MAY
immediately send HTTP/2 frames to such a server; servers can identify
these connections by the presence of the connection preface. This
only affects the establishment of HTTP/2 connections over cleartext
TCP; implementations that support HTTP/2 over TLS MUST use protocol
negotiation in TLS [TLS-ALPN].
Likewise, the …
```
=> Support HTTP2 Prior Knowledge

http.go
We had some internal reports of services logging warnings like "Couldn't send response body", with the underlying error being "http2: stream closed".
These errors occur as a result of the client closing the stream as we're still writing to it, which is a frequent and expected part of HTTP/2 operation, so we can safely log these at debug level.
=> Log http2: stream closed as debug-level

e2e_http1_test.go, e2e_http2_test.go, e2e_test.go, examples/simple.go, h2c.go, request_test.go, response_test.go, server.go
This allows configuring the standard Go http.Server timeouts on Typhon servers, and adds a new ServerOption interface that we can use to extend Typhon config in the future.
Sadly I couldn't get this working for h2c - this is due to a bug in Go where the original *http.Server configuration doesn't get propagated to h2c connections. See https://github.com/golang/go/issues/52868
=> Add support for server timeouts

errors.go
If we fail to read the entire body, we should propogate that error.
This will allow us to stop emitting this I/O error to Sentry.
Don't attempt to recover the partially read bytes - they might contain sensitive data, and putting them in a terror risks them being propogated to an unintended target.
=> error-filter: Propogate body read errors

request.go, response.go
We have been bitten by subtle bugs that are caused by this function being called on a value (and not a pointer to a value), combined with `consume == false`.
=> Warn that BodyBytes functions should be called on reference

router.go, router_test.go
These are very useful values to be able to access easily while processing requests. Let's make them public and reachable via the context.
=> Add public accessors for request pattern and method

request.go
One common pitfall of using typhon.NewRequest for standard HTTP usage is that it's easy to try and use it like a regular http.NewRequest and pass in a raw body (e.g. a []byte), expecting that to work the same - but then Typhon encodes the body as JSON. Now of course you could pass in an io.ReadCloser/io.Reader to avoid this, but you'd only know this from digging deep into the Typhon code, not from the docstrings!
This adds NewRawRequest as a bit of sugar to guide someone into the expected behaviour.
=> Add NewRawRequest
